### ISSUE TITLE
[BUG] Clicking on the Workbench tab throws an error 

### ISSUE THREAD

**Issue by aryanpingle** [INTO-CPS-Association/DTaaS#1103]
### Describe the bug

When I click on the workbench tab after logging in, I see this:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'icon')
TypeError: Cannot read properties of undefined (reading 'icon')
    at https://localhost/static/js/main.e809d595.js:75:53320
    at Array.map (<anonymous>)
    at https://localhost/static/js/main.e809d595.js:75:53253
    at I_ (https://localhost/static/js/main.e809d595.js:75:53341)
    at ho (https://localhost/static/js/main.e809d595.js:2:1450428)
    at Tl (https://localhost/static/js/main.e809d595.js:2:1510079)
    at Sc (https://localhost/static/js/main.e809d595.js:2:1499185)
    at fc (https://localhost/static/js/main.e809d595.js:2:1499113)
    at hc (https://localhost/static/js/main.e809d595.js:2:1498976)
    at ac (https://localhost/static/js/main.e809d595.js:2:1495756)
```

![image](https://github.com/user-attachments/assets/c7816711-4ba0-4a3f-aefd-d5507f153e79)

### To Reproduce

Start a local server (I'm using `compose.local.secure.yml`), and try clicking on the workbench tab after logging in.

It seems to originate from the latest commit ([Adds Digital Twin create and Library features](https://github.com/INTO-CPS-Association/DTaaS/commit/1b0e8d6c5c18d904027961b5863bbf4874f4b7b9)) since the tab opens correctly on the previous ones.

### Application Environment

Please provide the following information:

- OS: Windows 10
- Browse: Chrome
- DTaaS Release: Latest commit (1b0e8d6c5c18d904027961b5863bbf4874f4b7b9)

**Comment by prasadtalasila** [comment]
Similar error occurs when loading **Digital Twins** Tab of **Library Preview** page. The console gives a hint.

````console
chunk-4WY6JWTD.mjs:5605 Error handled by React Router default ErrorBoundary: TypeError: Cannot read properties of undefined (reading 'description')
    at lU (AssetCard.tsx:96:29)
    at ti (react-dom-client.production.js:4351:21)
    at $s (react-dom-client.production.js:6497:15)
    at il (react-dom-client.production.js:7473:14)
    at uu (react-dom-client.production.js:11305:14)
    at lu (react-dom-client.production.js:11182:37)
    at su (react-dom-client.production.js:11163:7)
    at Yc (react-dom-client.production.js:10690:9)
    at Bu (react-dom-client.production.js:12078:3)
    at MessagePort.R (scheduler.production.js:151:44)
qt @ chunk-4WY6JWTD.mjs:5605
ti @ react-dom-client.production.js:4351
$s @ react-dom-client.production.js:6497
il @ react-dom-client.production.js:7473
uu @ react-dom-client.production.js:11305
lu @ react-dom-client.production.js:11182
su @ react-dom-client.production.js:11163
Yc @ react-dom-client.production.js:10690
Bu @ react-dom-client.production.js:12078
R @ scheduler.production.js:151
chunk-4WY6JWTD.mjs:5605 Error handled by React Router default ErrorBoundary: TypeError: Cannot read properties of undefined (reading 'description')
    at lU (AssetCard.tsx:96:29)
    at ti (react-dom-client.production.js:4351:21)
    at $s (react-dom-client.production.js:6497:15)
    at il (react-dom-client.production.js:7473:14)
    at uu (react-dom-client.production.js:11305:14)
    at lu (react-dom-client.production.js:11182:37)
    at su (react-dom-client.production.js:11163:7)
    at Yc (react-dom-client.production.js:10728:40)
    at Bu (react-dom-client.production.js:12078:3)
    at MessagePort.R (scheduler.production.js:151:44)
qt @ chunk-4WY6JWTD.mjs:5605
ti @ react-dom-client.production.js:4351
$s @ react-dom-client.production.js:6497
il @ react-dom-client.production.js:7473
uu @ react-dom-client.production.js:11305
lu @ react-dom-client.production.js:11182
su @ react-dom-client.production.js:11163
Yc @ react-dom-client.production.js:10728
Bu @ react-dom-client.production.js:12078
R @ scheduler.production.js:151
react-dom-client.production.js:5892 TypeError: Cannot read properties of undefined (reading 'description')
    at lU (AssetCard.tsx:96:29)
    at ti (react-dom-client.production.js:4351:21)
    at $s (react-dom-client.production.js:6497:15)
    at il (react-dom-client.production.js:7473:14)
    at uu (react-dom-client.production.js:11305:14)
    at lu (react-dom-client.production.js:11182:37)
    at su (react-dom-client.production.js:11163:7)
    at Yc (react-dom-client.production.js:10728:40)
    at Bu (react-dom-client.production.js:12078:3)
    at MessagePort.R (scheduler.production.js:151:44)
ks @ react-dom-client.production.js:5892
Is @ react-dom-client.production.js:5909
Ns.i.componentDidCatch.e.callback @ react-dom-client.production.js:5949
_a @ react-dom-client.production.js:4216
Ta @ react-dom-client.production.js:4226
yl @ react-dom-client.production.js:8636
Ll @ react-dom-client.production.js:9046
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9050
bu @ react-dom-client.production.js:11660
fu @ react-dom-client.production.js:11520
Zc @ react-dom-client.production.js:10920
Yc @ react-dom-client.production.js:10826
Bu @ react-dom-client.production.js:12078
R @ scheduler.production.js:151
chunk-4WY6JWTD.mjs:5644 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'description')
    at lU (AssetCard.tsx:96:29)
    at ti (react-dom-client.production.js:4351:21)
    at $s (react-dom-client.production.js:6497:15)
    at il (react-dom-client.production.js:7473:14)
    at uu (react-dom-client.production.js:11305:14)
    at lu (react-dom-client.production.js:11182:37)
    at su (react-dom-client.production.js:11163:7)
    at Yc (react-dom-client.production.js:10728:40)
    at Bu (react-dom-client.production.js:12078:3)
    at MessagePort.R (scheduler.production.js:151:44)
componentDidCatch @ chunk-4WY6JWTD.mjs:5644
Ns.i.componentDidCatch.e.callback @ react-dom-client.production.js:5955
_a @ react-dom-client.production.js:4216
Ta @ react-dom-client.production.js:4226
yl @ react-dom-client.production.js:8636
Ll @ react-dom-client.production.js:9046
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9014
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9126
Kl @ react-dom-client.production.js:9904
Ll @ react-dom-client.production.js:9050
bu @ react-dom-client.production.js:11660
fu @ react-dom-client.production.js:11520
Zc @ react-dom-client.production.js:10920
Yc @ react-dom-client.production.js:10826
Bu @ react-dom-client.production.js:12078
R @ scheduler.production.js:151
```

**Comment by prasadtalasila** [comment]
PR #1456 resolves the issue
