### ISSUE TITLE
Jest `SyntaxError` caused by `strip-ansi` and `react-markdown` dependencies

### ISSUE THREAD

**Issue by VanessaScherma** [INTO-CPS-Association/DTaaS#902]
Running unit tests with Jest results in syntax errors due to importing the `strip-ansi` and `react-markdown` libraries. 

To view the error:
```
cd client
yarn jest test/unit/routes/digitaltwins/ExecutionFunctions.test.ts

```
This is the test that fails due to `SyntaxError: Cannot use import statement outside a module` caused by strip-ansi:
```
 FAIL  test/unit/routes/digitaltwins/ExecutionFunctions.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/vanessa/Documenti/DtaaS/DTaaS/client/node_modules/strip-ansi/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import ansiRegex from 'ansi-regex';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       6 | import DigitalTwin from 'util/gitlabDigitalTwin';
       7 | import { GitlabInstance } from 'util/gitlab';
    >  8 | import stripAnsi from 'strip-ansi';
         | ^
       9 | import { JobLog } from '../../components/asset/StartStopButton';
      10 |
      11 | export const handleButtonClick = (

      at Runtime.createScriptFromCode (node_modules/jest-config/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/route/digitaltwins/ExecutionFunctions.ts:8:1)
      at Object.<anonymous> (test/unit/routes/digitaltwins/ExecutionFunctions.test.ts:1:1)
```

This a test that fails due to `SyntaxError: Unexpected token 'export' `caused by react-markdown:
```
● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/vanessa/Documenti/DTaaS - branch con manage/DTaaS/client/node_modules/react-markdown/index.js:9
    export {Markdown as default, defaultUrlTransform} from './lib/index.js'
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       8 |     Typography,
       9 |   } from '@mui/material';
    > 10 |   import ReactMarkdown from 'react-markdown';
         |   ^
      11 |   import remarkGfm from 'remark-gfm';
      12 |
      13 |   interface DetailsDialogProps {

      at Runtime.createScriptFromCode (node_modules/jest-config/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/route/digitaltwins/DetailsDialog.tsx:10:3)
      at Object.<anonymous> (test/unit/routes/digitaltwins/DetailsDialog.test.tsx:4:1)
```

**Comment by prasadtalasila** [comment]
PR #1163 and #1220 fix this problem by not using these packages.
